### ISSUE TITLE
Ошибка отметки красного текста в одной конкретной фразе 

### ISSUE THREAD

**Issue by AlexDyatchenko** [agrudtsin/gramatist#36]
Утром мы вылетаем в Париж - We're flying to Paris in the morning
Детали на скриншоте.
![1](https://cloud.githubusercontent.com/assets/8981208/5628856/49cd8e88-95b5-11e4-827d-4e20118b3f9c.png)

**Comment by AlexDyatchenko** [comment]
![2](https://cloud.githubusercontent.com/assets/8981208/5629235/f571fe50-95b9-11e4-994d-5f8691f4fa26.png)

**Comment by agrudtsin** [comment]
Наверное это уже не актуально
