### ISSUE TITLE
После набора всей фразы корректно добавляю неверный символ и вижу "undefined"

### ISSUE THREAD

**Issue by AlexDyatchenko** [agrudtsin/gramatist#43]
They are on holiday
хотел в конец добавить s он сначала красным подсветил, потом убрал красное, потом серым написал undefined после последней буквы

**Comment by agrudtsin** [comment]
![image](https://cloud.githubusercontent.com/assets/1062309/5687447/5eb1303c-9855-11e4-931d-9ca885883182.png)
